### ISSUE TITLE
[Feature Request] Make the Mgmt. API Host and Port a configurable execution time parameters

### ISSUE THREAD

**Issue by mpurwar** [apigeecs/ApigeeBundleReaper#4]
Hello Sai,
We were trying to use this tool for our OPDK and reviewing the js files, seems that the host is the only configurable at execution time and port is hardcoded to default 443 HTTPS.

So the request is to make the Mgmt. API Host and Port a configurable execution time parameters.

Thanks!!

**Comment by ssvaidyanathan** [comment]
@muditpurwar - hey.. will work on this and let you know once done

**Comment by ssvaidyanathan** [comment]
@muditpurwar - have made the changes, please test and see if it works as expected

**Comment by ajaykumar55** [comment]
Hi Sai,
I have downloaded latest code and tried to use with the custom host and port but, getting below error. Could you please help me with this issue?

C:\ApigeeBundleReaper-master\src>npm -v
5.5.1

C:\ApigeeBundleReaper-master\src>node -v
v6.11.4

C:\ApigeeBundleReaper-master\src>node bundle-reaper.js -h http://xxxxxxxxxx.unix.gsm1800.org -p 8080 -a myusername mypassword -d 60 -o devlab -e dlab01-core -u no
{ Error: getaddrinfo ENOTFOUND http://xxxxxxxxxx.unix.gsm1800.org http://xxxxxxxxxx.unix.gsm1800.org:8080
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'http://xxxxxxxxxx.unix.gsm1800.org',
  host: 'http://xxxxxxxxxx.unix.gsm1800.org',
  port: '8080' }
{ Error: getaddrinfo ENOTFOUND http://xxxxxxxxxx.unix.gsm1800.org http://xxxxxxxxxx.unix.gsm1800.org:8080
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'http://xxxxxxxxxx.unix.gsm1800.org',
  host: 'http://xxxxxxxxxx.unix.gsm1800.org',
  port: '8080' }

**Comment by ssvaidyanathan** [comment]
@ajaykumar55 - you dont need to pass the protocol in the host parameter. Just pass the host, try with
```
node bundle-reaper.js -h xxxxxxxxxx.unix.gsm1800.org -p 8080 -a myusername mypassword -d 60 -o devlab -e dlab01-core -u no
```
NOTE: See if you can find the https end point of your management server

**Comment by ajaykumar55** [comment]
@ssvaidyanathan thanks, for your quick response. Is there an option to use http port? If not, would it be possible for you to update the script to support for http?

**Comment by ssvaidyanathan** [comment]
did you try the command ? what is the error?

**Comment by ajaykumar55** [comment]
Below is the error i see with http port 8080

C:\ApigeeBundleReaper-master\src>node bundle-reaper.js -h xxxxxxxxx.unix.gsm1900.org -p 8080 -a myusername mypassword -d 60 -o devlab -e dlab01-core -u no
{ Error: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:797:

    at exports._errnoException (util.js:1020:11)
    at WriteWrap.afterWrite (net.js:800:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }
{ Error: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:797:

    at exports._errnoException (util.js:1020:11)
    at WriteWrap.afterWrite (net.js:800:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }

**Comment by ssvaidyanathan** [comment]
Can you confirm you have access to the mgmt server from your machine ? Can you hit the mgmt server using curl or postman
```
curl -X GET \
  http://xxxxxxxxx.unix.gsm1900.org:8080/v1/o/devlab/e/dlab01-core/ \
  -H 'Authorization: Basic ****' \
  -H 'Content-Type: application/json'
```

Also make sure you are passing the base 64 encoded value of your username and password for -a argument. That is if you base 64 encoded value of your username:password is "abcd1234", then pass it as  `-a Basic abcd1234`

**Comment by ajaykumar55** [comment]
yes. I have postman on my machine and it works fine. Below is the curl from my postman

curl -X GET \
  http://xxxxxxxxxxxx.unix.gsm1900.org:8080/v1/o/devlab/e/dlab01-core/ \
  -H 'authorization: Basic xxxxxxxxxxxxxxxxxx' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: xxxxx-xxxxx-xxx-xxx-xxx-xxx'

**Comment by ssvaidyanathan** [comment]
Can we get on a call ?

**Comment by ajaykumar55** [comment]
I have tried to use -a Basic option and it didn't change the error.

Sure, please let me know your contact info. Thanks.

**Comment by ssvaidyanathan** [comment]
Please share me your email id, will send an invite..

**Comment by ajaykumar55** [comment]
Below is my email id. 
ajayaphani.anabheri@t-mobile.com 

I just got into another meeting. Could you please schedule our call at 1PM PST?? 

Thanks!

**Comment by ajaykumar55** [comment]
@ssvaidyanathan 

This is working fine with the new code changes you made. Was able to execute the script for on-prem env's with http port now. 

Thanks a lot for making the new enhancements to the script in short period. :)

Btw, i'm not seeing an option to close this issue. Maybe Mudit can close this or please go ahead and close it if you have permissions.

**Comment by ssvaidyanathan** [comment]
Thanks.. closing it
