### ISSUE TITLE
Error: Cannot find module 'commander'

### ISSUE THREAD

**Issue by tjain87** [apigeecs/ApigeeBundleReaper#5]
Hi,

I am trying to run the project but getting below error. Can you please help?

module.js:471
    throw err;
    ^
Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\apigee\ApigeeBundleReaper\src\bundle-reaper.js:1:77)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

Node version installed on my Windows machine is:

$ node --version
v6.11.4
$ npm --version
5.5.1

After cloning the project, ran npm install :
$ ls -lrt
total 76
-rw-r--r-- 1 tjai16 1049089 14638 Oct 16 14:13 getProxyStatus.js
-rw-r--r-- 1 tjai16 1049089  8898 Oct 16 14:13 reaper.js
-rw-r--r-- 1 tjai16 1049089   866 Oct 16 14:24 package.json
drwxr-xr-x 1 tjai16 1049089     0 Oct 17 09:38 node_modules/
-rw-r--r-- 1 tjai16 1049089 25985 Oct 17 09:38 package-lock.json

And trying to run 
node bundle-reaper.js -s https -h api.enterprise.apigee.com -p 443 -e test

Thanks
Tarun J.

**Comment by ssvaidyanathan** [comment]
HI @tjain87 - can you copy the node_modules directory from the package directory to the src directory and then try ? If that works, let me know, I will update the README to reflect that

**Comment by tjain87** [comment]
Hello @ssvaidyanathan Thanks. It works after moving node_modules directory from the package directory to the src directory. :+1:

**Comment by ssvaidyanathan** [comment]
Thanks @tjain87 for the update

Made changes to the README and the code. Moved the package.json from package directory to src
ecbdb47c3aeb860a14de7ba297bb37be30c9e426
