### ISSUE TITLE
Revisions of no traffic proxies

### ISSUE THREAD

**Issue by tjain87** [apigeecs/ApigeeBundleReaper#7]
Hi,

Does this considers the traffic of latest deployed proxy revision or all revisions (although not deployed)?

Thanks
Tarun J.

**Comment by ssvaidyanathan** [comment]
@tjain87 - Its for the proxy that is deployed (irrespective of the revision). I guess revision doesnt matter. As long as the proxy is not serving traffic it comes up in the output.

Please reopen the issue if needed
